-- MULCV GeoArchives - recensement terrain initial
-- A executer apres 001_create_schema.sql

CREATE TABLE IF NOT EXISTS site_census_surveys (
  id CHAR(36) PRIMARY KEY,
  site_id CHAR(36) NOT NULL,
  captured_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  capture_mode VARCHAR(40) NOT NULL DEFAULT 'mobile',
  respondent_name TEXT NOT NULL,
  respondent_role VARCHAR(120) NOT NULL,
  respondent_phone VARCHAR(60) NULL,
  respondent_email VARCHAR(180) NULL,
  road_condition VARCHAR(80) NOT NULL DEFAULT 'passable',
  last_mile_condition VARCHAR(80) NOT NULL DEFAULT 'accessible',
  travel_time_minutes INT NOT NULL DEFAULT 0,
  network_quality VARCHAR(80) NOT NULL DEFAULT 'moyenne',
  building_condition VARCHAR(80) NOT NULL DEFAULT 'stable',
  storage_condition VARCHAR(80) NOT NULL DEFAULT 'acceptable',
  water_risk_level VARCHAR(80) NOT NULL DEFAULT 'modere',
  security_risk_level VARCHAR(80) NOT NULL DEFAULT 'modere',
  seasonal_constraints TEXT NULL,
  survey_notes TEXT NULL,
  photo_references JSON NULL,
  gps_accuracy_meters DECIMAL(10,2) NULL,
  gps_captured_at DATETIME NULL,
  checklist_vehicle_access BOOLEAN NOT NULL DEFAULT FALSE,
  checklist_loading_area BOOLEAN NOT NULL DEFAULT FALSE,
  checklist_site_signage BOOLEAN NOT NULL DEFAULT FALSE,
  checklist_archives_separated BOOLEAN NOT NULL DEFAULT FALSE,
  checklist_shelving_available BOOLEAN NOT NULL DEFAULT FALSE,
  checklist_humidity_observed BOOLEAN NOT NULL DEFAULT FALSE,
  checklist_pest_observed BOOLEAN NOT NULL DEFAULT FALSE,
  checklist_fire_extinguisher BOOLEAN NOT NULL DEFAULT FALSE,
  checklist_backup_power BOOLEAN NOT NULL DEFAULT FALSE,
  checklist_immediate_risk_reported BOOLEAN NOT NULL DEFAULT FALSE,
  raw_payload JSON NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY site_census_surveys_site_unique (site_id),
  KEY site_census_surveys_captured_idx (captured_at),
  CONSTRAINT site_census_surveys_site_fk FOREIGN KEY (site_id) REFERENCES archive_sites(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
